app:
  name: "jimeng-auto"
  host: "0.0.0.0"
  port: 18001
  urls:
    jimeng: "https://jimeng.jianying.com/ai-tool/generate"
    gemini: "https://gemini.google.com/app"

browser:
  headless: false
  timeout: 30000
  channel: "chrome"
  width: 1920
  height: 1080

task:
  timeout: 120000

storage:
  profile_dir: "cache/profiles"
  image_cache_dir: "cache/images"
  download_cache_dir: "cache/downloads"
  download_url_prefix: "http://localhost:8000"


database:
  # url: "postgresql+asyncpg://postgres:123456@192.168.120.224:5432/jimeng"
  url: "postgresql+asyncpg://postgres:secret@127.0.0.1:5432/jimeng"
  pool_size: 10
  max_overflow: 20



scanner:
  enabled: true
  interval: 60
  wait_time: 10
  retry_limit: 3

