server_addr: ":17781"
db:
  dsn: "host=192.168.120.224 user=postgres password=123456 dbname=ai-film-studio port=5432 sslmode=disable"
master_agent_path: "configs/agents/master.yaml"
jimeng:
  base_url: "http://127.0.0.1:18001"
models:
  default: "ark/minimax-m2.7"
  providers:
    ark:
      title: "火山引擎"
      api_key: "0c6dab72-3465-4635-9c2a-da689d2c1e00"
      base_url: "https://ark.cn-beijing.volces.com/api/v3"
      driver_type: "ark"
      models:
        gemma4:26b:
          title: "gemma4:26b"
          temperature: 1.0
          max_tokens: 8192
          thinking: true
          use_functions: true
          input:
            - "text"
    google:
      title: "google"
      api_key: "0c6dab72-3465-4635-9c2a-da689d2c1e00"
      base_url: "https://ark.cn-beijing.volces.com/api/v3"
      driver_type: "ark"
      models:
        gemma4:26b:
          title: "gemma4:26b"
          temperature: 1.0
          max_tokens: 8192
          thinking: true
          use_functions: true
          input:
            - "text"
    ollama:
      title: "OLLAMA"
      api_key: "ollama"
      base_url: "http://localhost:11434/api"
      driver_type: "openai"
      models:
        gemma4:26b:
          title: "gemma4:26b"
          temperature: 1.0
          max_tokens: 8192
          thinking: true
          use_functions: true
          input:
            - "text"
    minimax:
      title: "MiniMax"
      api_key: "sk-cp-s1rksxmWNo1I4AZuCusJUDcOa4i1mllHGaDvDs5Dn2Mr-wjLJsEJ8cJq6TzEZWgjSc2pK8qe5wOBP5kDQH1BllGbMHLk5-E9xlMscZZUJdwOH9TZcwFy0mc"
      base_url: "https://api.minimaxi.com/v1"
      driver_type: "openai"
      models:
        minimax-m2.7:
          title: "MiniMax-M2.7"
          temperature: 1.0
          max_tokens: 8192
          thinking: true
          use_functions: true
          input:
            - "text"
        minimax-m2.5:
          title: "minimax-m2.5"
          temperature: 1.0
          max_tokens: 8192
          thinking: true
          use_functions: true
          input:
            - "text"