import {
  Board,
  Scene,
  StoryPage,
  Shot,
  Keyframe,
  Character,
  Prop,
  Prompt,
  SceneType,
  StoryPageWeather,
  ShotState,
  CameraShotType,
  CameraAngle,
  CameraMovement,
  CharacterType,
} from "./types";

export const mockBoards: Board[] = [
  {
    id: "board-1",
    projectId: "project-1",
    name: "第一章：校园篇",
    description: "故事的开端，主角登场",
    sortOrder: 1,
    status: "draft",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "board-2",
    projectId: "project-1",
    name: "第二章：冒险开始",
    description: "主角踏上冒险旅程",
    sortOrder: 2,
    status: "draft",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const mockScenes: Scene[] = [
  {
    id: "scene-1",
    name: "教室",
    description: "高中教室，日常场景",
    type: SceneType.Interior,
  },
  {
    id: "scene-2",
    name: "操场",
    description: "学校操场，户外场景",
    type: SceneType.Exterior,
  },
];

export const mockCharacters: Character[] = [
  {
    id: "char-1",
    name: "小明",
    description: "男主角，高中生",
    type: CharacterType.Lead,
  },
  {
    id: "char-2",
    name: "小红",
    description: "女主角，高中生",
    type: CharacterType.Lead,
  },
  {
    id: "char-3",
    name: "老师",
    description: "班主任",
    type: CharacterType.Supporting,
  },
];

export const mockProps: Prop[] = [
  {
    id: "prop-1",
    name: "书包",
    description: "小明背的书包",
  },
  {
    id: "prop-2",
    name: "篮球",
    description: "操场上的篮球",
  },
];

export const mockPrompts: Prompt[] = [
  {
    id: "prompt-1",
    text: "A classroom scene with sunlight streaming through windows, anime style",
    mediaUrls: ["https://picsum.photos/seed/class1/800/450"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prompt-2",
    text: "Close-up shot of main character walking in school corridor",
    mediaUrls: ["https://picsum.photos/seed/corridor1/800/450"],
    createdAt: new Date().toISOString(),
  },
];

export const mockStoryPages: StoryPage[] = [
  {
    id: "sp-1",
    boardId: "board-1",
    title: "开学第一天",
    desc: "新学期开学，小明走进教室",
    sortOrder: 1,
    status: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    storyTime: "晨",
    weather: "晴",
  },
  {
    id: "sp-2",
    boardId: "board-1",
    title: "自我介绍",
    desc: "班主任让每位同学自我介绍",
    sortOrder: 2,
    status: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    storyTime: "晨",
    weather: "晴",
  },
  {
    id: "sp-3",
    boardId: "board-1",
    title: "课间活动",
    desc: "小明和小红在操场相遇",
    sortOrder: 3,
    status: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    storyTime: "午",
    weather: "阴",
  },
];

export const mockShots: Shot[] = [
  {
    id: "shot-1",
    storyPageId: "sp-1",
    content: "小明背着书包走进教室",
    orderNum: 1,
    state: ShotState.Draft,
    characterIds: ["char-1"],
    sceneIds: ["scene-1"],
    propIds: ["prop-1"],
    sceneType: SceneType.Interior,
    weather: StoryPageWeather.Sunny,
    script: "小明背着书包走进教室",
    directorIntent: "展现校园的青春气息",
    promptId: "prompt-1",
  },
  {
    id: "shot-2",
    storyPageId: "sp-1",
    content: "小明看到小红，两人目光相遇",
    orderNum: 2,
    state: ShotState.Draft,
    characterIds: ["char-1", "char-2"],
    sceneIds: ["scene-1"],
    script: "小明看到小红，两人目光相遇",
    directorIntent: "制造浪漫氛围",
    promptId: "prompt-2",
  },
  {
    id: "shot-3",
    storyPageId: "sp-3",
    content: "第三镜头内容",
    orderNum: 1,
    state: ShotState.Draft,
    characterIds: ["char-1", "char-2"],
    sceneIds: ["scene-2"],
    propIds: ["prop-2"],
    sceneType: SceneType.Exterior,
    weather: StoryPageWeather.Cloudy,
    script: "课间时间，小红在操场打篮球",
    directorIntent: "展现小红的活力",
  },
];

export const mockKeyframes: Keyframe[] = [
  {
    id: "kf-1",
    shotId: "shot-1",
    frameNumber: 1,
    imageUrl: "https://picsum.photos/seed/kf1/800/450",
    thumbnailUrl: "https://picsum.photos/seed/kf1/400/225",
    description: "教室门口，阳光明媚，小明推门而入",
    promptId: "prompt-1",
    actionDescription: "小明推开门，背着书包走进来",
    cameraSettings: { focalLength: "35mm", aperture: "f/2.8" },
    orderNum: 1,
    cameraShotType: CameraShotType.Medium,
    cameraAngle: CameraAngle.EyeLevel,
    cameraMovement: CameraMovement.Static,
    duration: "3s",
    soundEffects: "门吱呀一声",
  },
  {
    id: "kf-2",
    shotId: "shot-1",
    frameNumber: 2,
    imageUrl: "https://picsum.photos/seed/kf2/800/450",
    thumbnailUrl: "https://picsum.photos/seed/kf2/400/225",
    description: "小明的近景表情",
    actionDescription: "小明环顾四周，露出微笑",
    cameraSettings: { focalLength: "50mm", aperture: "f/1.8" },
    orderNum: 2,
    cameraShotType: CameraShotType.CloseUp,
    cameraAngle: CameraAngle.EyeLevel,
    cameraMovement: CameraMovement.PushIn,
    duration: "2s",
    soundEffects: "轻快的背景音乐",
  },
  {
    id: "kf-3",
    shotId: "shot-2",
    frameNumber: 1,
    imageUrl: "https://picsum.photos/seed/kf3/800/450",
    thumbnailUrl: "https://picsum.photos/seed/kf3/400/225",
    description: "小红坐在窗边，阳光照在她身上",
    actionDescription: "小红转头看向门口",
    cameraSettings: { focalLength: "85mm", aperture: "f/1.4" },
    orderNum: 1,
    cameraShotType: CameraShotType.CloseUp,
    cameraAngle: CameraAngle.HighAngle,
    cameraMovement: CameraMovement.Static,
    duration: "2s",
    soundEffects: "",
  },
];
